# Generated by Django 3.2.7 on 2021-09-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='Title',
            new_name='title',
        ),
    ]
